version: "3.8"
services:
  nginx-reveal-drei:
    depends_on:
      - presentation-api
      - reveal-drei
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "4444:4444"

  reveal-drei:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4222:4222"
    volumes:
      - ./app:/app/app
      - ./HOC:/app/HOC
      - ./hooks:/app/hooks
      - ./components:/app/components
      - ./containers:/app/containers
      - ./store:/app/store
      - ./styles:/app/styles
      - ./public:/app/public
      - ./plugin:/app/plugin
      - ./utils:/app/utils
      - ./types:/app/types
      - ./nginx:/app/nginx
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    depends_on:
      - presentation-api
    restart: unless-stopped

  presentation-api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api/presentation
    volumes:
      - ./api/presentation:/app
      - /api/node_modules
    environment:
      - PORT=4223
      - NODE_ENV=development
      - DB_NAME=presentation
      - ROLE=admin
    restart: unless-stopped
