version: "3.8"
services:
  nginx-reveal-drei:
    depends_on:
      - presentation-api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "4110:4110"

  reveal-drei:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4111:4111"
    volumes:
      - ./app:/app/app
      - ./components:/app/components
      - ./containers:/app/containers
      - ./store:/app/store
      - ./styles:/app/styles
      - ./public:/app/public
      - ./plugin:/app/plugin
      - ./utils:/app/utils
      - ./types:/app/types
      - ./nginx:/app/nginx
      - ./js:/app/js
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    depends_on:
      - presentation-api
    restart: unless-stopped

  presentation-api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api/presentation
    volumes:
      - ./api/presentation:/app
      - /api/node_modules
    environment:
      - PORT=4112
      - NODE_ENV=development
      - DB_NAME=presentation
      - ROLE=admin
    restart: unless-stopped
